"""Cria tabela DetalhesProcesso

Revision ID: 2b59ccf048f7
Revises: 
Create Date: 2025-06-13 15:11:40.165904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b59ccf048f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalhes_processo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.Column('coordenacao', sa.String(length=120), nullable=True),
    sa.Column('lideranca', sa.String(length=120), nullable=True),
    sa.Column('data_inspecao', sa.Date(), nullable=True),
    sa.Column('inspetor', sa.String(length=120), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=True),
    sa.Column('coop', sa.String(length=120), nullable=True),
    sa.Column('tipo', sa.String(length=120), nullable=True),
    sa.Column('data_execucao', sa.Date(), nullable=True),
    sa.Column('interno_externo', sa.String(length=50), nullable=True),
    sa.Column('tipo_autorizacao', sa.String(length=120), nullable=True),
    sa.Column('tipo_erro', sa.String(length=120), nullable=True),
    sa.Column('gravidade', sa.String(length=120), nullable=True),
    sa.Column('desvio_atencao', sa.String(length=10), nullable=True),
    sa.Column('reversao', sa.String(length=10), nullable=True),
    sa.Column('fluxos', sa.String(length=255), nullable=True),
    sa.Column('solicitante', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalhes_processo')
    # ### end Alembic commands ###
