"""Primeira migração no MySQL

Revision ID: 5d44748ea9b5
Revises: 
Create Date: 2025-06-21 02:22:26.028669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d44748ea9b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colaborador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('senha_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('processo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('data_analise', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('imagem', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaborador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalhes_processo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.Column('coordenacao', sa.String(length=120), nullable=True),
    sa.Column('lideranca', sa.String(length=120), nullable=True),
    sa.Column('data_inspecao', sa.Date(), nullable=True),
    sa.Column('inspetor', sa.String(length=120), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=True),
    sa.Column('coop', sa.String(length=120), nullable=True),
    sa.Column('tipo', sa.String(length=120), nullable=True),
    sa.Column('data_execucao', sa.Date(), nullable=True),
    sa.Column('interno_externo', sa.String(length=50), nullable=True),
    sa.Column('tipo_autorizacao', sa.String(length=120), nullable=True),
    sa.Column('tipo_erro', sa.String(length=120), nullable=True),
    sa.Column('gravidade', sa.String(length=120), nullable=True),
    sa.Column('desvio_atencao', sa.String(length=10), nullable=True),
    sa.Column('reversao', sa.String(length=10), nullable=True),
    sa.Column('fluxos', sa.String(length=255), nullable=True),
    sa.Column('solicitante', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalhes_processo')
    op.drop_table('processo')
    op.drop_table('senha_usuario')
    op.drop_table('colaborador')
    # ### end Alembic commands ###
