"""Adiciona tabela SenhaUsuario

Revision ID: cc3b428bb2bd
Revises: 2b59ccf048f7
Create Date: 2025-06-15 15:23:40.537668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3b428bb2bd'
down_revision = '2b59ccf048f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('senha_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('processo', schema=None) as batch_op:
        batch_op.alter_column('data_analise',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processo', schema=None) as batch_op:
        batch_op.alter_column('data_analise',
               existing_type=sa.DATETIME(),
               nullable=True)

    op.drop_table('senha_usuario')
    # ### end Alembic commands ###
